### ISSUE TITLE
LIGGGHTS Support

### ISSUE THREAD

**Issue by MRudey** [ThFriedrich/lammps_vscode#1]
I am using LIGGGHTS a lot which is a DEM code forked/cloned from LAMMPS. Do you plan on extending the syntax with additional LIGGGHTS commands? Most of them are shared so it works out of the box. I have already started adding a few to `lmps.tmLanguage.json` after installing your extension. I could create a pull request with the changes made.
I just added most commands to `keyword.general_command.lmps` and `keyword.fix_command.lmps` although some of them are additional arguments not necessarily fix commands. Therefore, one could also create deeper patterns such as: `keyword.fix_command.wall_command.lmps` or `keyword.fix_command.mesh_command.lmps`. This would need much more time and might not be needed, as I am personally just interested in the syntax highlighting to identify keywords etc.

**Comment by ThFriedrich** [comment]
I didn't plan on implementing LIGGGHTS support, but it seems to me it may be a valuable addition to the project and I appreciate the suggestion. I think creating deeper patterns is not that big a deal. It may not be particularly useful at the moment, but it'd be nice to keep the structure tidy. It makes maintenance and potential further developments and additions a lot easier. If you cannot invest the time to add new patterns, you may just go ahead with the pull request. I can sort out the patterns as well.

**Comment by ThFriedrich** [comment]
I added subgroups and included LIGGGHTS(R)-PUBLIC keywords as they are listed in the documentation. I guess this should be fairly complete. The vsix package is updated too and I also published the update to the marketplace already.
