### ISSUE TITLE
Feat: Checks before runtime

### ISSUE THREAD

**Issue by arn-all** [ThFriedrich/lammps_vscode#11]
As proposed in #10 , a more general idea is to consider checks that could be easily done by the extension when writing a script, to catch errors before runtime : 

- Missing or empty input files in `read_data` or `pair_coeff` commands
- Non-existing path for output destination (`dump`, `log`, `write_data`)
- Invalid format of input files (`pair_coeff`, dump files, final `neb` configuration file, ...)
- Reuse of an ID when declaring a command
- ...

I guess that possibilities are endless, and virtually impossible to automatically find. Though, I am confident that catching the most common ones is always interesting. The list can be completed later...

Edit : some users could be writing _template_ scripts that are to be filled by some template engine (e.g jinja2). Any template markup like `{{hello}}` should be ignored.

**Comment by arn-all** [comment]
I'm thinking of a "dry-run" mode, which could be an option to catch many mistakes, but I'm really not sure, as there'd probably be many pitfalls. 

The idea is to run lammps in a temporary folder, with a modified version of the lammps script, in which run commands are set to 1 timestep, and  minimize or neb commands to a very tolerant criterion. It would allow Lammps to go through the whole script very quickly, and to let it complain about any illegal commands. But I guess that complex runtime structures (loops, ... ) would make it much more complicate to do. Do you think it's worth discussing in a separate issue ?

**Comment by ThFriedrich** [comment]
Those are some interesting approaches. I am not sure about the dry-run idea. I think there is indeed a lot of pitfalls as you say. Maybe it'd be wise to keep this extension independent of the actual Lammps program unless we were to include some custom debugger functionality at some point. For now, I think it'd be more reasonable to create some kind of Linter to catch common mistakes before runtime. That could be just a set of functions to be run when the document changes and add Problems/Errors via the API. I went ahead and gave that a try, prepared a dedicated module for linting functions, and implemented a check for existing files on read-commands in  [this commit](https://github.com/ThFriedrich/lammps_vscode/commit/3a17a557dfe66936ff2188ac3e1d608102f83765). It seems to work nicely so far. 

![image](https://user-images.githubusercontent.com/47680554/81501806-8f203580-92da-11ea-8067-2b3c3a4f12d0.png)

However, I am not sure if we could run into performance issues as the number of checks increases. Maybe it is worth considering to set up a  [language server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide), which would be running in separate processes. Lammps Scripts are usually not very long though I suppose, so performance may not be much of a concern after all. I don't know.

I created separate issues and a project for all the document checking. I guess this is easier to manage.

**Comment by arn-all** [comment]
Hi Thomas,

Just letting you know that based on a [user request](https://matsci.org/t/syntax-check-of-input-script-before-simulation-run/38117), there is now a [kind of dry-run mode for LAMMPS](https://docs.lammps.org/latest/Run_options.html#skiprun), which can be activated via the CLI (`-skiprun`). The idea is to set a timeout to 0, so each run/minimize operation will be skipped. It has caveats (e.g conditional execution) but can help spot some mistakes in input files. 
We could add a `Run : Single-Task (dry-run)` to [task_fncs.ts](https://github.com/ThFriedrich/lammps_vscode/blob/5c677423462f77145227cf69d1e43c8e326a10d2/src/task_fcns.ts) in the future if you agree (though it won't work for older LAMMPS versions than the patch released on yesterday).

**Comment by ThFriedrich** [comment]
The dry-run feature was added in [this commit](https://github.com/ThFriedrich/lammps_vscode/commit/d713821aff87a1d66f79f832e12e221ff2f98be0) and ships with version 1.7.0
