### ISSUE TITLE
Use relative paths for files

### ISSUE THREAD

**Issue by jpkrowe** [ThFriedrich/lammps_vscode#49]
I use relative paths to my files (e.g. data and restart files) and this always gives an error as vscode is looking for the file relative to the workspace directory.

It would be nice for the file to be searched for relative to the directory that the input script is in, in addition to being looked for relative to the workspace directory

**Comment by ThFriedrich** [comment]
Hi @jpkrowe  . Thanks for your Bug-Report.
I've just pushed an update that changes the path-checks to relate to the script-path, rather than the current working directory. I will close the issue. Please reopen if problems persist. The update will ship with the next release shortly.

**Comment by Fratorhe** [comment]
Hi, 
Same happens when trying to run a task. 
If the task requires data and it is located in the same folder, VSCode looks at the scope relative to the workspace and gives error when trying to run the task. 
Any suggestions on this? 
Thanks a lot!
