### ISSUE TITLE
create outline

### ISSUE THREAD

**Issue by thangckt** [ThFriedrich/lammps_vscode#52]
Dear developers,

Can you let an ability to show an outline when opening the LAMMPS script in vscode. This will help to quickly navigate to a part of code in the case of long file.
We can define a convention to specify the heading, for example `##!# ...`, `##!## ...`,

Thank you.

**Comment by ThFriedrich** [comment]
Hi @thangckt 
I've just pushed an update that provides Symbols, using the extension-specific folding start-marker('#[' = Start Marker, '#]' = End Marker) as reference point:
![image](https://github.com/ThFriedrich/lammps_vscode/assets/47680554/363c192c-5fae-4367-8b8e-a3946aa1175b)
This provides an Outline as you probably expect. This feature will ship with the next release shortly. I'm gonna close this issue as I feel confident that implements what you're asking for. If there's anything more, feel free to reopen the issue. :)

Best
Thomas

**Comment by thangckt** [comment]
It is looked great

Thank you @ThFriedrich
