### ISSUE TITLE
Treat "CPU" as a file

### ISSUE THREAD

**Issue by fanpeizhou** [ThFriedrich/lammps_vscode#55]
**The file CPU does not exist.**
When using the `read_data` command, the extension always reports this `error` in log.lammps file.

**To Reproduce**
1. use `read_data` command

**Screenshots**
![image](https://i.imgur.com/g6jL0eM.png)

**Desktop:**
 - Lammps Version: 23 Jun 2022
 - Extension Version: Latest

**Comment by ThFriedrich** [comment]
Hi @fanpeizhou ,

thanks for reporting this. However, I wouldn't really label this a bug. You seem to be looking at log files, which the extension wasn't really meant to deal with. I can see how this would be useful though. We could consider implementing something like a file-selector specific switch to turn off the pre-run checks for files starting with "log." or something. This isn't very robust though, as log files may have any name. So I am not sure if there's an elegant solution for this. Ideas appreciated.

Best
Thomas

**Comment by fanpeizhou** [comment]
Hi @ThFriedrich,

Thank you very much for your reply. You are right. After all this extension was designed for in files rather than log files, I'll delete the 'bug' label and I'm sorry for this. The solution you mentioned, I think that works since the log file that lammps created starts with "log." by default.

By the way, I just tested the latest extension, which works nicely. Thank you for this improvement.

Kind regards,
Chaohong

**Comment by fanpeizhou** [comment]
Oops, I don't know how to change the label. The only thing I can do now is to close this issue.
