### ISSUE TITLE
Provide Snippets

### ISSUE THREAD

**Issue by ThFriedrich** [ThFriedrich/lammps_vscode#9]
Perhaps it would be useful to provide snippets for very common structures and commands.

**Comment by ThFriedrich** [comment]
I prepared a file to allow snippets and added a few examples [here](https://github.com/ThFriedrich/lammps_vscode/blob/master/snippets/lmps.json). This was all manual work so far, but maybe the generation of this could be automated. In particular, I find the suggestions for "styles" very helpful:
![Screenshot at 2020-04-17 13-31-38](https://user-images.githubusercontent.com/47680554/79565036-20bbcf00-80b0-11ea-9669-d9f30b714a90.png)
 
Difficulties arise because it is not possible to distinguish optional arguments and then all the keyword/value-stuff could spoil the whole thing. 
@arn-all Whats your opinion on this?

**Comment by arn-all** [comment]
Hi,
It seems very encouraging, though I don't understand what you mean by ; 
> Difficulties arise because it is not possible to distinguish optional arguments and then all the keyword/value-stuff could spoil the whole thing.

**Comment by ThFriedrich** [comment]
I removed most of the snippets in favour of a similarly working autocompletion behaviour using automatically generated SnippetStrings (issue   #16)
